---
title: "DS325_Project-3"
author: "Johnny Carstens & Matthew Bushnell"
date: "12/2/2021"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=F, message=F, cache=T, eval=T)
```

# Task 1: Visualizing the Data

```{r}
library(tidyverse)
library(olsrr)
library(GGally)
library(ggfortify)
library(mdsr)

Originaldata <- read.csv("Project3Sample4000.csv")

data <- Originaldata %>%
  separate(c_jail_in, c("inDay","inMonth","inYear")) %>%
  separate(c_jail_out,c("outDay","outMonth","outYear")) %>%
  mutate(
    daysInJail = ((as.integer(outYear)*365)+(as.integer(outMonth)*30)+(as.integer(outDay)))-((as.integer(inYear)*365)+(as.integer(inMonth)*30)+(as.integer(inDay)))
  ) %>%
  select(!c(name, dob, inDay, inMonth, inYear, outDay, outMonth, outYear, RiskRecidScreeningDate, c_charge_desc)) %>%
  mutate(
    totalPriors = priorsCount+juvFelonyCount+juvMisdemeanerCount+juvOtherCount
  ) %>%
  select(!c(priorsCount,juvFelonyCount,juvMisdemeanerCount,juvOtherCount,ageCat,days_b_screening_arrest,c_days_from_compas,c_charge_degree,race))

ggplot(data=data,aes(x=sex, fill=as.factor(isRecid))) + 
  geom_bar(position="dodge") +
  labs(fill="Reoffended",x="Gender",y="Count", title = "Gender vs. Reoffended")

ggplot(data=data,aes(fill=as.factor(isRecid), x=RiskRecidDecileScore)) +
  geom_density(alpha=.3) + 
  facet_wrap(~race) +
  labs(title="Risk of Recidivism Density and Reoffended",x="Risk of Recidivism Score",y="Density",fill="Reoffended")

ggplot(data=data,aes(x=priorsCount,fill=as.factor(isRecid))) +
  geom_density(alpha=.3) +
  labs(title="Priors Density and Reoffended",x="Priors",y="Density",fill="Reoffended")

ggplot(data=data,aes(x=c_charge_degree,fill=as.factor(isRecid))) +
  geom_bar(position="dodge") +
  labs(title="Charge Degree and Reoffended",x="Charge Degree",y="Count",fill="Reoffended")
```

